package htl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptEXTRACTField = new ConceptDescriptorBuilder("htl.structure.EXTRACTField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58efba2L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1464646648772631374L, "regex")).properties("regex").childDescriptors(new ConceptDescriptorBuilder.Link(6950931094434075899L, "innerField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58f1979L), true, false, false)).children(new String[]{"innerField"}, new boolean[]{false}).create();
  /*package*/ final ConceptDescriptor myConceptGETField = new ConceptDescriptorBuilder("htl.structure.GETField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df588cbb9L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1464646648772631465L, "url")).properties("url").childDescriptors(new ConceptDescriptorBuilder.Link(1464646648772623491L, "extractField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58efba2L), true, false, false), new ConceptDescriptorBuilder.Link(1464646648772648608L, "paramsField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58f59c8L), true, true, false)).children(new String[]{"extractField", "paramsField"}, new boolean[]{false, true}).create();
  /*package*/ final ConceptDescriptor myConceptHTTPTest = new ConceptDescriptorBuilder("htl.structure.HTTPTest", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df5880dbdL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(1464646648772219041L, "getField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df588cbb9L), true, true, false), new ConceptDescriptorBuilder.Link(1464646648773452898L, "postField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58f59a0L), true, true, false)).children(new String[]{"getField", "postField"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptINNERField = new ConceptDescriptorBuilder("htl.structure.INNERField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58f1979L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1464646648772631372L, "regex")).properties("regex").create();
  /*package*/ final ConceptDescriptor myConceptPARAMField = new ConceptDescriptorBuilder("htl.structure.PARAMField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58f59c8L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptPOSTField = new ConceptDescriptorBuilder("htl.structure.POSTField", MetaIdFactory.conceptId(0x93b576952f9f479dL, 0x90b23a57a5b5ed93L, 0x1453785df58f59a0L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1464646648773452417L, "url")).properties("url").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptEXTRACTField, myConceptGETField, myConceptHTTPTest, myConceptINNERField, myConceptPARAMField, myConceptPOSTField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0k, conceptFqName)) {
      case 0:
        return myConceptEXTRACTField;
      case 1:
        return myConceptGETField;
      case 2:
        return myConceptHTTPTest;
      case 3:
        return myConceptINNERField;
      case 4:
        return myConceptPARAMField;
      case 5:
        return myConceptPOSTField;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0k = new String[]{"htl.structure.EXTRACTField", "htl.structure.GETField", "htl.structure.HTTPTest", "htl.structure.INNERField", "htl.structure.PARAMField", "htl.structure.POSTField"};
}
