package htl.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 2:
        return new HTTPTest_BehaviorDescriptor();
      case 1:
        return new GETField_BehaviorDescriptor();
      case 0:
        return new EXTRACTField_BehaviorDescriptor();
      case 3:
        return new INNERField_BehaviorDescriptor();
      case 5:
        return new POSTField_BehaviorDescriptor();
      case 4:
        return new PARAMField_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"htl.structure.EXTRACTField", "htl.structure.GETField", "htl.structure.HTTPTest", "htl.structure.INNERField", "htl.structure.PARAMField", "htl.structure.POSTField"};
}
