package htl.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EXTRACTField_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public EXTRACTField_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "htl.structure.EXTRACTField";
  }
}
