package htl.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class INNERField_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public INNERField_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "htl.structure.INNERField";
  }
}
