package htl.sandbox;

/*Generated by MPS */

import de.skandy.httpclientexample.HTTPClient;

public class DropBoxTest {


  public static String GetSampleFile() {
    String url = "https://dl.dropboxusercontent.com/u/3005814/test.html";
    String response = HTTPClient.processGet(url);
    response = HTTPClient.extractString(response, "<body>.*</body>", "<p.*?>\\w*</p>");

    return response;
  }


}
